# <a href = "https://www.youtube.com/watch?v=4HKqjENq9OU&t=8s"> KNN - Predict whether a person will have diabetes or not </a>

Dataset - Diabetes Data

In [140]:
# importing library

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [141]:
data = pd.read_csv('/Users/adityaagarwal/Aditya Ag/Jupyter Notebook/Machine Learning Algorithms/KNN algorithm/Knn on Diabeties Data/diabetes.csv')
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [142]:
# check for null values
data.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [143]:
# Checking Columns with "0" values
cols_names = data.columns

for i in cols_names:
    # Column Name
    print(i)
    col_data = data[data[i]==0]
    print(col_data,"\n")
    print("Total number of rows with 0 value in", i ,"is", col_data.shape[0],"\n")
    print("#"*100)

Pregnancies
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
4              0      137             40             35      168  43.1
16             0      118             84             47      230  45.8
45             0      180             66             39        0  42.0
57             0      100             88             60      110  46.8
58             0      146             82              0        0  40.5
..           ...      ...            ...            ...      ...   ...
713            0      134             58             20      291  26.4
727            0      141             84             26        0  32.4
736            0      126             86             27      120  27.4
753            0      181             88             44      510  43.3
757            0      123             72              0        0  36.3

     DiabetesPedigreeFunction  Age  Outcome
4                       2.288   33        1
16                      0.551   31        1
45                      1.893   25        1
57                      0.962   31        0
58                      1.781   44        0
..                        ...  ...      ...
713                     0.352   21        0
727                     0.433   22        0
736                     0.515   21        0
753                     0.222   26        1
757                     0.258   52        1

[111 rows x 9 columns]

Total number of rows with 0 value in Pregnancies is 111

####################################################################################################
Glucose
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
75             1        0             48             20        0  24.7
182            1        0             74             20       23  27.7
342            1        0             68             35        0  32.0
349            5        0             80             32        0  41.0
502            6        0             68             41        0  39.0

     DiabetesPedigreeFunction  Age  Outcome
75                      0.140   22        0
182                     0.299   21        0
342                     0.389   22        0
349                     0.346   37        1
502                     0.727   41        1

Total number of rows with 0 value in Glucose is 5

####################################################################################################
BloodPressure
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
7             10      115              0              0        0  35.3
15             7      100              0              0        0  30.0
49             7      105              0              0        0   0.0
60             2       84              0              0        0   0.0
78             0      131              0              0        0  43.2
81             2       74              0              0        0   0.0
172            2       87              0             23        0  28.9
193           11      135              0              0        0  52.3
222            7      119              0              0        0  25.2
261            3      141              0              0        0  30.0
266            0      138              0              0        0  36.3
269            2      146              0              0        0  27.5
300            0      167              0              0        0  32.3
332            1      180              0              0        0  43.3
336            0      117              0              0        0  33.8
347            3      116              0              0        0  23.5
357           13      129              0             30        0  39.9
426            0       94              0              0        0   0.0
430            2       99              0              0        0  22.2
435            0      141              0              0        0  42.4
453            2      119              0              0        0  19.6
468            8      120              0              0        0  30.0
484            0      145              0              0        0  44.2
494            3       80              0              0        0   0.0
522            6      114              0              0        0   0.0
533            6       91              0              0        0  29.8
535            4      132              0              0        0  32.9
589            0       73              0              0        0  21.1
601            6       96              0              0        0  23.7
604            4      183              0              0        0  28.4
619            0      119              0              0        0  32.4
643            4       90              0              0        0  28.0
697            0       99              0              0        0  25.0
703            2      129              0              0        0  38.5
706           10      115              0              0        0   0.0

     DiabetesPedigreeFunction  Age  Outcome
7                       0.134   29        0
15                      0.484   32        1
49                      0.305   24        0
60                      0.304   21        0
78                      0.270   26        1
81                      0.102   22        0
172                     0.773   25        0
193                     0.578   40        1
222                     0.209   37        0
261                     0.761   27        1
266                     0.933   25        1
269                     0.240   28        1
300                     0.839   30        1
332                     0.282   41        1
336                     0.932   44        0
347                     0.187   23        0
357                     0.569   44        1
426                     0.256   25        0
430                     0.108   23        0
435                     0.205   29        1
453                     0.832   72        0
468                     0.183   38        1
484                     0.630   31        1
494                     0.174   22        0
522                     0.189   26        0
533                     0.501   31        0
535                     0.302   23        1
589                     0.342   25        0
601                     0.190   28        0
604                     0.212   36        1
619                     0.141   24        1
643                     0.610   31        0
697                     0.253   22        0
703                     0.304   41        0
706                     0.261   30        1

Total number of rows with 0 value in BloodPressure is 35

####################################################################################################
SkinThickness
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
2              8      183             64              0        0  23.3
5              5      116             74              0        0  25.6
7             10      115              0              0        0  35.3
9              8      125             96              0        0   0.0
10             4      110             92              0        0  37.6
..           ...      ...            ...            ...      ...   ...
757            0      123             72              0        0  36.3
758            1      106             76              0        0  37.5
759            6      190             92              0        0  35.5
762            9       89             62              0        0  22.5
766            1      126             60              0        0  30.1

     DiabetesPedigreeFunction  Age  Outcome
2                       0.672   32        1
5                       0.201   30        0
7                       0.134   29        0
9                       0.232   54        1
10                      0.191   30        0
..                        ...  ...      ...
757                     0.258   52        1
758                     0.197   26        0
759                     0.278   66        1
762                     0.142   33        0
766                     0.349   47        1

[227 rows x 9 columns]

Total number of rows with 0 value in SkinThickness is 227

####################################################################################################
Insulin
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
5              5      116             74              0        0  25.6
7             10      115              0              0        0  35.3
..           ...      ...            ...            ...      ...   ...
761            9      170             74             31        0  44.0
762            9       89             62              0        0  22.5
764            2      122             70             27        0  36.8
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        1
1                       0.351   31        0
2                       0.672   32        1
5                       0.201   30        0
7                       0.134   29        0
..                        ...  ...      ...
761                     0.403   43        1
762                     0.142   33        0
764                     0.340   27        0
766                     0.349   47        1
767                     0.315   23        0

[374 rows x 9 columns]

Total number of rows with 0 value in Insulin is 374

####################################################################################################
BMI
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
9              8      125             96              0        0  0.0
49             7      105              0              0        0  0.0
60             2       84              0              0        0  0.0
81             2       74              0              0        0  0.0
145            0      102             75             23        0  0.0
371            0      118             64             23       89  0.0
426            0       94              0              0        0  0.0
494            3       80              0              0        0  0.0
522            6      114              0              0        0  0.0
684            5      136             82              0        0  0.0
706           10      115              0              0        0  0.0

     DiabetesPedigreeFunction  Age  Outcome
9                       0.232   54        1
49                      0.305   24        0
60                      0.304   21        0
81                      0.102   22        0
145                     0.572   21        0
371                     1.731   21        0
426                     0.256   25        0
494                     0.174   22        0
522                     0.189   26        0
684                     0.640   69        0
706                     0.261   30        1

Total number of rows with 0 value in BMI is 11

####################################################################################################
DiabetesPedigreeFunction
Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

Total number of rows with 0 value in DiabetesPedigreeFunction is 0

####################################################################################################
Age
Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

Total number of rows with 0 value in Age is 0

####################################################################################################
Outcome
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1              1       85             66             29        0  26.6
3              1       89             66             23       94  28.1
5              5      116             74              0        0  25.6
7             10      115              0              0        0  35.3
10             4      110             92              0        0  37.6
..           ...      ...            ...            ...      ...   ...
762            9       89             62              0        0  22.5
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome
1                       0.351   31        0
3                       0.167   21        0
5                       0.201   30        0
7                       0.134   29        0
10                      0.191   30        0
..                        ...  ...      ...
762                     0.142   33        0
763                     0.171   63        0
764                     0.340   27        0
765                     0.245   30        0
767                     0.315   23        0

[500 rows x 9 columns]

Total number of rows with 0 value in Outcome is 500

####################################################################################################

In [152]:
# Replace zeroes with NAN values
zero_not_accepted = ['Glucose', 'BloodPressure', 'SkinThickness', 'BMI', 'Insulin']

In [153]:
# Imputing mean values in Columns which have 0 Value
for i in zero_not_accepted:
    data[i] = data[i].replace(0, np.NaN)
    mean = int(data[i].mean(skipna=True))
    data[i] = data[i].fillna(mean)

print(data.isna().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [154]:
# split dataset
X = data.iloc[:, 0:8]
y = data.iloc[:, 8]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, test_size=0.2)

In [155]:
# Shape of the dataset
print("X_train:", X_train.shape, "\t y_train:", y_train.shape, "\t X_test:", X_test.shape, "\t y_test:", y_test.shape)

X_train: (614, 8) 	 y_train: (614,) 	 X_test: (154, 8) 	 y_test: (154,)

In [156]:
# Feature scaling
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [157]:
# Define the model: Init K-NN
classifier = KNeighborsClassifier(n_neighbors=11, p=2, metric='euclidean')

In [158]:
# Fit Model
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=11)

In [159]:
# Predict the test set results
y_pred = classifier.predict(X_test)
print(y_pred)
print(y_pred.shape)

[1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0
 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 1 0 1 0 1 0
 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 0]
(154,)

In [160]:
# Evaluating the Model
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:",cm)
# F1 Score
print("F1 Score for the testing data and prediction dataset:",round(f1_score(y_test, y_pred)*100,3),"\n")
# Accuracy
print("Accuracy of the model is",round(accuracy_score(y_test, y_pred)*100, 2),"\n")
# Classification report
print("Classification Report", classification_report(y_pred, y_test))

Confusion Matrix: [[94 13]
 [15 32]]
F1 Score for the testing data and prediction dataset: 69.565

Accuracy of the model is 81.82

Classification Report               precision    recall  f1-score   support

           0       0.88      0.86      0.87       109
           1       0.68      0.71      0.70        45

    accuracy                           0.82       154
   macro avg       0.78      0.79      0.78       154
weighted avg       0.82      0.82      0.82       154

In [164]:
y_test.T

661    1
122    0
113    0
14     1
529    0
      ..
476    1
482    0
230    1
527    0
380    0
Name: Outcome, Length: 154, dtype: int64

In [167]:
dict = {"y_test":y_test, "y_pred":y_pred}

In [182]:
submission = pd.DataFrame(dict)
submission.to_csv("submission.csv")
submission.sample(10)

     y_test  y_pred
671       0       0
451       1       0
103       0       0
362       0       0
374       0       1
68        0       0
672       0       0
471       0       1
479       0       0
583       0       0

In [181]:
# Printing rows which do not have same y_test and y_pred data
submission[submission['y_test']!= submission['y_pred']]

     y_test  y_pred
577       1       0
744       0       1
285       0       1
374       0       1
648       1       0
40        0       1
419       1       0
198       1       0
683       1       0
578       0       1
756       0       1
451       1       0
622       0       1
499       0       1
242       1       0
548       0       1
638       1       0
608       0       1
267       0       1
471       0       1
214       1       0
386       1       0
409       1       0
48        1       0
261       1       0
568       0       1
476       1       0
230       1       0