## Watch the video on [Rob Mulla](https://www.youtube.com/@robmulla) Youtube Channel
## The video link is [Here](https://www.youtube.com/watch?v=DkjCaAMBGWM)

In [7]:
import pandas as pd
import sys
import warnings
warnings.filterwarnings('ignore')
print(sys.version)
print('pandas version', pd.__version__)

3.9.13 (main, Aug 25 2022, 18:29:29)
[Clang 12.0.0 ]
pandas version 1.4.4

## Reading from files

In [2]:
## Mac
path = "/Users/adityaagarwal/Library/CloudStorage/OneDrive-NortheasternUniversity/Data-Science-datasets/Flight Status Prediction"
df = pd.read_parquet(path)

In [3]:
df = pd.read_parquet("D:\OneDrive - Northeastern University\Data-Science-datasets\
Flight Status Prediction/Combined_Flights_2022.parquet")

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\OneDrive - Northeastern University\\Data-Science-datasetsFlight Status Prediction/Combined_Flights_2022.parquet'

## Dataframe basics

In [15]:
pd.set_option("display.max_columns", 500)

In [16]:
df.head(3)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,1228.0,0.0,40.0,72.0,65.0,212.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4301,C5,20445,C5,N21144,4301,11921,1192102,31921,"Grand Junction, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,17.0,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,848.0,0.0,55.0,77.0,80.0,295.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4299,C5,20445,C5,N16170,4299,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,16.0,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0

In [17]:
df.sample(3, random_state=42)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
324021,2022-03-19,SkyWest Airlines Inc.,ASE,DEN,False,False,1831,1826.0,0.0,-5.0,1923.0,0.0,31.0,62.0,57.0,125.0,2022,1,3,19,6,UA,UA_CODESHARE,19977,UA,5745,OO,20304,OO,N794SK,5745,10372,1037205,30372,"Aspen, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1800-1859,19.0,1845.0,1916.0,7.0,1933,-10.0,0.0,-1.0,1900-1959,1,0
34739,2022-02-16,SkyWest Airlines Inc.,TYS,DEN,False,False,1605,1605.0,0.0,0.0,1812.0,35.0,194.0,212.0,247.0,1162.0,2022,1,2,16,3,UA,UA_CODESHARE,19977,UA,5733,OO,20304,OO,N127SY,5733,15412,1541205,35412,"Knoxville, TN",TN,47,Tennessee,54,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1600-1659,9.0,1614.0,1728.0,44.0,1737,35.0,1.0,2.0,1700-1759,5,0
304494,2022-01-18,American Airlines Inc.,LAX,OGG,False,False,1719,1714.0,0.0,-5.0,2052.0,3.0,314.0,330.0,338.0,2486.0,2022,1,1,18,2,AA,AA,19805,AA,205,AA,19805,AA,N400AN,205,12892,1289208,32575,"Los Angeles, CA",CA,6,California,91,13830,1383002,33830,"Kahului, HI",HI,15,Hawaii,2,0.0,-1.0,1700-1759,14.0,1728.0,2042.0,10.0,2049,3.0,0.0,0.0,2000-2059,10,0

In [18]:
df.sample(frac=0.000001, random_state=42)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
324021,2022-03-19,SkyWest Airlines Inc.,ASE,DEN,False,False,1831,1826.0,0.0,-5.0,1923.0,0.0,31.0,62.0,57.0,125.0,2022,1,3,19,6,UA,UA_CODESHARE,19977,UA,5745,OO,20304,OO,N794SK,5745,10372,1037205,30372,"Aspen, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1800-1859,19.0,1845.0,1916.0,7.0,1933,-10.0,0.0,-1.0,1900-1959,1,0
34739,2022-02-16,SkyWest Airlines Inc.,TYS,DEN,False,False,1605,1605.0,0.0,0.0,1812.0,35.0,194.0,212.0,247.0,1162.0,2022,1,2,16,3,UA,UA_CODESHARE,19977,UA,5733,OO,20304,OO,N127SY,5733,15412,1541205,35412,"Knoxville, TN",TN,47,Tennessee,54,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1600-1659,9.0,1614.0,1728.0,44.0,1737,35.0,1.0,2.0,1700-1759,5,0
304494,2022-01-18,American Airlines Inc.,LAX,OGG,False,False,1719,1714.0,0.0,-5.0,2052.0,3.0,314.0,330.0,338.0,2486.0,2022,1,1,18,2,AA,AA,19805,AA,205,AA,19805,AA,N400AN,205,12892,1289208,32575,"Los Angeles, CA",CA,6,California,91,13830,1383002,33830,"Kahului, HI",HI,15,Hawaii,2,0.0,-1.0,1700-1759,14.0,1728.0,2042.0,10.0,2049,3.0,0.0,0.0,2000-2059,10,0
205451,2022-01-23,Southwest Airlines Co.,LAS,BWI,False,False,1515,1533.0,18.0,18.0,2302.0,27.0,251.0,260.0,269.0,2106.0,2022,1,1,23,7,WN,WN,19393,WN,312,WN,19393,WN,N7828A,312,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,10821,1082106,30852,"Baltimore, MD",MD,24,Maryland,35,1.0,1.0,1500-1559,15.0,1548.0,2259.0,3.0,2235,27.0,1.0,1.0,2200-2259,9,0

In [19]:
df.columns

Index(['FlightDate', 'Airline', 'Origin', 'Dest', 'Cancelled', 'Diverted',
       'CRSDepTime', 'DepTime', 'DepDelayMinutes', 'DepDelay', 'ArrTime',
       'ArrDelayMinutes', 'AirTime', 'CRSElapsedTime', 'ActualElapsedTime',
       'Distance', 'Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek',
       'Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
       'DOT_ID_Marketing_Airline', 'IATA_Code_Marketing_Airline',
       'Flight_Number_Marketing_Airline', 'Operating_Airline',
       'DOT_ID_Operating_Airline', 'IATA_Code_Operating_Airline',
       'Tail_Number', 'Flight_Number_Operating_Airline', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'DestCityName',
       'DestState', 'DestStateFips', 'DestStateName', 'DestWac', 'DepDel15',
       'DepartureDelayGroups', 'DepTimeBlk', 'TaxiOut', 'WheelsOff',
       'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrDelay', 'ArrDel15',
       'ArrivalDelayGroups', 'ArrTimeBlk', 'DistanceGroup',
       'DivAirportLandings'],
      dtype='object')

In [20]:
df.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            590532, 590533, 590534, 590535, 590536, 590537, 590538, 590539,
            590540, 590541],
           dtype='int64', length=4078318)

## Dataframe summary

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4078318 entries, 0 to 590541
Data columns (total 61 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   FlightDate                               datetime64[ns]
 1   Airline                                  object
 2   Origin                                   object
 3   Dest                                     object
 4   Cancelled                                bool
 5   Diverted                                 bool
 6   CRSDepTime                               int64
 7   DepTime                                  float64
 8   DepDelayMinutes                          float64
 9   DepDelay                                 float64
 10  ArrTime                                  float64
 11  ArrDelayMinutes                          float64
 12  AirTime                                  float64
 13  CRSElapsedTime                           float64
 14  ActualElapsedTime                        float64
 15  Distance                                 float64
 16  Year                                     int64
 17  Quarter                                  int64
 18  Month                                    int64
 19  DayofMonth                               int64
 20  DayOfWeek                                int64
 21  Marketing_Airline_Network                object
 22  Operated_or_Branded_Code_Share_Partners  object
 23  DOT_ID_Marketing_Airline                 int64
 24  IATA_Code_Marketing_Airline              object
 25  Flight_Number_Marketing_Airline          int64
 26  Operating_Airline                        object
 27  DOT_ID_Operating_Airline                 int64
 28  IATA_Code_Operating_Airline              object
 29  Tail_Number                              object
 30  Flight_Number_Operating_Airline          int64
 31  OriginAirportID                          int64
 32  OriginAirportSeqID                       int64
 33  OriginCityMarketID                       int64
 34  OriginCityName                           object
 35  OriginState                              object
 36  OriginStateFips                          int64
 37  OriginStateName                          object
 38  OriginWac                                int64
 39  DestAirportID                            int64
 40  DestAirportSeqID                         int64
 41  DestCityMarketID                         int64
 42  DestCityName                             object
 43  DestState                                object
 44  DestStateFips                            int64
 45  DestStateName                            object
 46  DestWac                                  int64
 47  DepDel15                                 float64
 48  DepartureDelayGroups                     float64
 49  DepTimeBlk                               object
 50  TaxiOut                                  float64
 51  WheelsOff                                float64
 52  WheelsOn                                 float64
 53  TaxiIn                                   float64
 54  CRSArrTime                               int64
 55  ArrDelay                                 float64
 56  ArrDel15                                 float64
 57  ArrivalDelayGroups                       float64
 58  ArrTimeBlk                               object
 59  DistanceGroup                            int64
 60  DivAirportLandings                       int64
dtypes: bool(2), datetime64[ns](1), float64(18), int64(23), object(17)
memory usage: 1.8+ GB

In [12]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
Index: 4078318 entries, 0 to 590541
Columns: 61 entries, FlightDate to DivAirportLandings
dtypes: bool(2), datetime64[ns](1), float64(18), int64(23), object(17)
memory usage: 1.8+ GB

In [13]:
df.describe()

,FlightDate,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,DOT_ID_Marketing_Airline,Flight_Number_Marketing_Airline,DOT_ID_Operating_Airline,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginStateFips,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestStateFips,DestWac,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,DistanceGroup,DivAirportLandings
count,4078318,4.078318e+06,3.957885e+06,3.957823e+06,3.957823e+06,3.954079e+06,3.944916e+06,3.944916e+06,4.078318e+06,3.944916e+06,4.078318e+06,4078318.0,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,4.078318e+06,3.957823e+06,3.957823e+06,3.955652e+06,3.955652e+06,3.954076e+06,3.954076e+06,4.078318e+06,3.944916e+06,3.944916e+06,3.944916e+06,4.078318e+06,4.078318e+06
mean,2022-04-18 12:10:43.903097600,1.329587e+03,1.334374e+03,1.601494e+01,1.309049e+01,1.457886e+03,1.578307e+01,1.110075e+02,1.413211e+02,1.358624e+02,7.978657e+02,2022.0,1.741207e+00,4.083803e+00,1.571131e+01,4.005566e+00,1.983101e+04,2.562115e+03,1.999122e+04,2.562145e+03,1.265994e+04,1.265998e+06,3.175708e+04,2.746504e+01,5.399368e+01,1.265990e+04,1.265994e+06,3.175704e+04,2.746550e+01,5.399338e+01,2.184625e-01,2.141248e-01,1.697375e+01,1.356576e+03,1.455073e+03,7.894387e+00,1.486058e+03,7.528486e+00,2.164715e-01,-6.256103e-02,3.663516e+00,3.685098e-03
min,2022-01-01 00:00:00,1.000000e+00,1.000000e+00,0.000000e+00,-7.800000e+01,1.000000e+00,0.000000e+00,8.000000e+00,-4.800000e+01,1.400000e+01,3.100000e+01,2022.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.939300e+04,1.000000e+00,1.939300e+04,1.000000e+00,1.013500e+04,1.013506e+06,3.007000e+04,1.000000e+00,1.000000e+00,1.013500e+04,1.013506e+06,3.007000e+04,1.000000e+00,1.000000e+00,0.000000e+00,-2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+02,0.000000e+00,-2.000000e+00,1.000000e+00,0.000000e+00
25%,2022-02-25 00:00:00,9.140000e+02,9.170000e+02,0.000000e+00,-5.000000e+00,1.046000e+03,0.000000e+00,6.000000e+01,8.900000e+01,8.300000e+01,3.680000e+02,2022.0,1.000000e+00,2.000000e+00,8.000000e+00,2.000000e+00,1.979000e+04,1.105000e+03,1.979000e+04,1.105000e+03,1.129200e+04,1.129202e+06,3.069300e+04,1.200000e+01,3.300000e+01,1.129200e+04,1.129202e+06,3.069300e+04,1.200000e+01,3.300000e+01,0.000000e+00,-1.000000e+00,1.100000e+01,9.320000e+02,1.044000e+03,4.000000e+00,1.103000e+03,-1.400000e+01,0.000000e+00,-1.000000e+00,2.000000e+00,0.000000e+00
50%,2022-04-19 00:00:00,1.320000e+03,1.325000e+03,0.000000e+00,-2.000000e+00,1.500000e+03,0.000000e+00,9.400000e+01,1.240000e+02,1.190000e+02,6.430000e+02,2022.0,2.000000e+00,4.000000e+00,1.600000e+01,4.000000e+00,1.980500e+04,2.228000e+03,1.997700e+04,2.228000e+03,1.288900e+04,1.288903e+06,3.145300e+04,2.700000e+01,4.400000e+01,1.288900e+04,1.288903e+06,3.145300e+04,2.700000e+01,4.400000e+01,0.000000e+00,-1.000000e+00,1.500000e+01,1.338000e+03,1.456000e+03,6.000000e+00,1.513000e+03,-5.000000e+00,0.000000e+00,-1.000000e+00,3.000000e+00,0.000000e+00
75%,2022-06-11 00:00:00,1.735000e+03,1.744000e+03,1.100000e+01,1.100000e+01,1.914000e+03,1.000000e+01,1.410000e+02,1.710000e+02,1.670000e+02,1.035000e+03,2022.0,2.000000e+00,6.000000e+00,2.300000e+01,6.000000e+00,1.997700e+04,3.877000e+03,2.037800e+04,3.877000e+03,1.402700e+04,1.402702e+06,3.246700e+04,4.200000e+01,8.100000e+01,1.402700e+04,1.402702e+06,3.246700e+04,4.200000e+01,8.100000e+01,0.000000e+00,0.000000e+00,1.900000e+01,1.758000e+03,1.909000e+03,9.000000e+00,1.920000e+03,1.000000e+01,0.000000e+00,0.000000e+00,5.000000e+00,0.000000e+00
max,2022-07-31 00:00:00,2.359000e+03,2.400000e+03,7.223000e+03,7.223000e+03,2.400000e+03,7.232000e+03,7.270000e+02,6.900000e+02,7.640000e+02,5.095000e+03,2022.0,3.000000e+00,7.000000e+00,3.100000e+01,7.000000e+00,2.043600e+04,9.680000e+03,2.050000e+04,9.680000e+03,1.686900e+04,1.686901e+06,3.610100e+04,7.800000e+01,9.300000e+01,1.686900e+04,1.686901e+06,3.610100e+04,7.800000e+01,9.300000e+01,1.000000e+00,1.200000e+01,2.210000e+02,2.400000e+03,2.400000e+03,2.900000e+02,2.359000e+03,7.232000e+03,1.000000e+00,1.200000e+01,1.100000e+01,9.000000e+00
std,NaN,4.904801e+02,5.056219e+02,5.231498e+01,5.332016e+01,5.431841e+02,5.198424e+01,6.996246e+01,7.179635e+01,7.185501e+01,5.914742e+02,0.0,7.037563e-01,1.998918e+00,8.760122e+00,2.007050e+00,2.760907e+02,1.745826e+03,3.767694e+02,1.745873e+03,1.522713e+03,1.522711e+05,1.320296e+03,1.670547e+01,2.664820e+01,1.522718e+03,1.522716e+05,1.320286e+03,1.670567e+01,2.664849e+01,4.132030e-01,2.345973e+00,9.495407e+00,5.075580e+02,5.378428e+02,6.663118e+00,5.185078e+02,5.524625e+01,4.118393e-01,2.487442e+00,2.320848e+00,1.141331e-01

In [14]:
df[["Airline"]].describe()

                       Airline
count                  4078318
unique                      21
top     Southwest Airlines Co.
freq                    731925

In [15]:
df.shape, len(df)

((4078318, 61), 4078318)

## Subsetting Columns

In [16]:
df[['FlightDate', 'Airline', 'Origin']]

       FlightDate                                    Airline Origin
0      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    GJT
1      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    HRL
2      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    DRO
3      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    IAH
4      2022-04-04  Commutair Aka Champlain Enterprises, Inc.    DRO
...           ...                                        ...    ...
590537 2022-03-31                          Republic Airlines    MSY
590538 2022-03-17                          Republic Airlines    CLT
590539 2022-03-08                          Republic Airlines    ALB
590540 2022-03-25                          Republic Airlines    EWR
590541 2022-03-07                          Republic Airlines    EWR

[4078318 rows x 3 columns]

In [17]:
df[df.columns[:5]]

,FlightDate,Airline,Origin,Dest,Cancelled
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False
...,...,...,...,...,...
590537,2022-03-31,Republic Airlines,MSY,EWR,False
590538,2022-03-17,Republic Airlines,CLT,EWR,True
590539,2022-03-08,Republic Airlines,ALB,ORD,False
590540,2022-03-25,Republic Airlines,EWR,PIT,False
590541,2022-03-07,Republic Airlines,EWR,RDU,False

In [18]:
df[[c for c in df.columns if 'Time' in c]]

,CRSDepTime,DepTime,ArrTime,AirTime,CRSElapsedTime,ActualElapsedTime,DepTimeBlk,CRSArrTime,ArrTimeBlk
0,1133,1123.0,1228.0,40.0,72.0,65.0,1100-1159,1245,1200-1259
1,732,728.0,848.0,55.0,77.0,80.0,0700-0759,849,0800-0859
2,1529,1514.0,1636.0,47.0,70.0,82.0,1500-1559,1639,1600-1659
3,1435,1430.0,1547.0,57.0,90.0,77.0,1400-1459,1605,1600-1659
4,1135,1135.0,1251.0,49.0,70.0,76.0,1100-1159,1245,1200-1259
...,...,...,...,...,...,...,...,...,...
590537,1949,2014.0,234.0,NaN,185.0,NaN,1900-1959,2354,2300-2359
590538,1733,1817.0,NaN,NaN,129.0,NaN,1700-1759,1942,1900-1959
590539,1700,2318.0,59.0,135.0,158.0,161.0,1700-1759,1838,1800-1859
590540,2129,2322.0,939.0,NaN,86.0,NaN,2100-2159,2255,2200-2259
590541,1154,1148.0,1556.0,NaN,99.0,NaN,1100-1159,1333,1300-1359

## Select dtypes

In [19]:
df.select_dtypes('int')

,CRSDepTime,Year,Quarter,Month,DayofMonth,DayOfWeek,DOT_ID_Marketing_Airline,Flight_Number_Marketing_Airline,DOT_ID_Operating_Airline,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginStateFips,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestStateFips,DestWac,CRSArrTime,DistanceGroup,DivAirportLandings
0,1133,2022,2,4,4,1,19977,4301,20445,4301,11921,1192102,31921,8,82,11292,1129202,30325,8,82,1245,1,0
1,732,2022,2,4,4,1,19977,4299,20445,4299,12206,1220605,32206,48,74,12266,1226603,31453,48,74,849,2,0
2,1529,2022,2,4,4,1,19977,4298,20445,4298,11413,1141307,30285,8,82,11292,1129202,30325,8,82,1639,2,0
3,1435,2022,2,4,4,1,19977,4296,20445,4296,12266,1226603,31453,48,74,11973,1197302,31973,28,53,1605,2,0
4,1135,2022,2,4,4,1,19977,4295,20445,4295,11413,1141307,30285,8,82,11292,1129202,30325,8,82,1245,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590537,1949,2022,1,3,31,4,19977,3621,20452,3621,13495,1349505,33495,22,72,11618,1161802,31703,34,21,2354,5,1
590538,1733,2022,1,3,17,4,19977,3437,20452,3437,11057,1105703,31057,37,36,11618,1161802,31703,34,21,1942,3,0
590539,1700,2022,1,3,8,2,19977,3413,20452,3413,10257,1025702,30257,36,22,13930,1393007,30977,17,41,1838,3,0
590540,2129,2022,1,3,25,5,19977,3450,20452,3450,11618,1161802,31703,34,21,14122,1412202,30198,42,23,2255,2,1
590541,1154,2022,1,3,7,1,19977,3585,20452,3585,11618,1161802,31703,34,21,14492,1449202,34492,37,36,1333,2,1

## Select as series vs dataframe

In [20]:
df['Airline']

0         Commutair Aka Champlain Enterprises, Inc.
1         Commutair Aka Champlain Enterprises, Inc.
2         Commutair Aka Champlain Enterprises, Inc.
3         Commutair Aka Champlain Enterprises, Inc.
4         Commutair Aka Champlain Enterprises, Inc.
                            ...
590537                            Republic Airlines
590538                            Republic Airlines
590539                            Republic Airlines
590540                            Republic Airlines
590541                            Republic Airlines
Name: Airline, Length: 4078318, dtype: object

In [21]:
df[['Airline']]

                                          Airline
0       Commutair Aka Champlain Enterprises, Inc.
1       Commutair Aka Champlain Enterprises, Inc.
2       Commutair Aka Champlain Enterprises, Inc.
3       Commutair Aka Champlain Enterprises, Inc.
4       Commutair Aka Champlain Enterprises, Inc.
...                                           ...
590537                          Republic Airlines
590538                          Republic Airlines
590539                          Republic Airlines
590540                          Republic Airlines
590541                          Republic Airlines

[4078318 rows x 1 columns]

## loc and iloc

In [22]:
df.iloc[1, 3]

'IAH'

In [23]:
df.iloc[:5, :5]

  FlightDate                                    Airline Origin Dest  Cancelled
0 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    GJT  DEN      False
1 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    HRL  IAH      False
2 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    DRO  DEN      False
3 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    IAH  GPT      False
4 2022-04-04  Commutair Aka Champlain Enterprises, Inc.    DRO  DEN      False

In [24]:
df.iloc[[5]]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
5,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DEN,TUL,False,False,955,952.0,0.0,-3.0,1238.0,0.0,77.0,105.0,106.0,541.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4294,C5,20445,C5,N11191,4294,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,15370,1537002,34653,"Tulsa, OK",OK,40,Oklahoma,73,0.0,-1.0,0900-0959,25.0,1017.0,1234.0,4.0,1240,-2.0,0.0,-1.0,1200-1259,3,0

In [25]:
df.iloc[:, 1]

0         Commutair Aka Champlain Enterprises, Inc.
1         Commutair Aka Champlain Enterprises, Inc.
2         Commutair Aka Champlain Enterprises, Inc.
3         Commutair Aka Champlain Enterprises, Inc.
4         Commutair Aka Champlain Enterprises, Inc.
                            ...
590537                            Republic Airlines
590538                            Republic Airlines
590539                            Republic Airlines
590540                            Republic Airlines
590541                            Republic Airlines
Name: Airline, Length: 4078318, dtype: object

In [26]:
df.iloc[:, [1, 2]]

                                          Airline Origin
0       Commutair Aka Champlain Enterprises, Inc.    GJT
1       Commutair Aka Champlain Enterprises, Inc.    HRL
2       Commutair Aka Champlain Enterprises, Inc.    DRO
3       Commutair Aka Champlain Enterprises, Inc.    IAH
4       Commutair Aka Champlain Enterprises, Inc.    DRO
...                                           ...    ...
590537                          Republic Airlines    MSY
590538                          Republic Airlines    CLT
590539                          Republic Airlines    ALB
590540                          Republic Airlines    EWR
590541                          Republic Airlines    EWR

[4078318 rows x 2 columns]

In [27]:
df.loc[:, ['Airline', 'Origin']]

                                          Airline Origin
0       Commutair Aka Champlain Enterprises, Inc.    GJT
1       Commutair Aka Champlain Enterprises, Inc.    HRL
2       Commutair Aka Champlain Enterprises, Inc.    DRO
3       Commutair Aka Champlain Enterprises, Inc.    IAH
4       Commutair Aka Champlain Enterprises, Inc.    DRO
...                                           ...    ...
590537                          Republic Airlines    MSY
590538                          Republic Airlines    CLT
590539                          Republic Airlines    ALB
590540                          Republic Airlines    EWR
590541                          Republic Airlines    EWR

[4078318 rows x 2 columns]

## loc filter expressions

In [28]:
df.loc[df['Airline'] == 'Spirit Air Lines']

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
407040,2022-04-01,Spirit Air Lines,FLL,ORD,True,False,2025,NaN,NaN,NaN,NaN,NaN,NaN,193.0,NaN,1182.0,2022,2,4,1,5,NK,NK,20416,NK,1,NK,20416,NK,N669NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,NaN,NaN,2000-2059,NaN,NaN,NaN,NaN,2238,NaN,NaN,NaN,2200-2259,5,0
407041,2022-04-02,Spirit Air Lines,FLL,ORD,True,False,2147,NaN,NaN,NaN,NaN,NaN,NaN,192.0,NaN,1182.0,2022,2,4,2,6,NK,NK,20416,NK,1,NK,20416,NK,N680NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,NaN,NaN,2100-2159,NaN,NaN,NaN,NaN,2359,NaN,NaN,NaN,2300-2359,5,0
407042,2022-04-03,Spirit Air Lines,FLL,ORD,False,False,2147,211.0,264.0,264.0,421.0,262.0,163.0,192.0,190.0,1182.0,2022,2,4,3,7,NK,NK,20416,NK,1,NK,20416,NK,N661NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,12.0,2100-2159,18.0,229.0,412.0,9.0,2359,262.0,1.0,12.0,2300-2359,5,0
407043,2022-04-04,Spirit Air Lines,FLL,ORD,False,False,2147,2227.0,40.0,40.0,39.0,40.0,157.0,192.0,192.0,1182.0,2022,2,4,4,1,NK,NK,20416,NK,1,NK,20416,NK,N680NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,2.0,2100-2159,25.0,2252.0,29.0,10.0,2359,40.0,1.0,2.0,2300-2359,5,0
407044,2022-04-05,Spirit Air Lines,FLL,ORD,False,False,2200,2252.0,52.0,52.0,58.0,46.0,164.0,192.0,186.0,1182.0,2022,2,4,5,2,NK,NK,20416,NK,1,NK,20416,NK,N681NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,3.0,2200-2259,13.0,2305.0,49.0,9.0,12,46.0,1.0,3.0,0001-0559,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142478,2022-03-27,Spirit Air Lines,EWR,LAS,False,False,1700,1705.0,5.0,5.0,2019.0,58.0,297.0,321.0,374.0,2227.0,2022,1,3,27,7,NK,NK,20416,NK,993,NK,20416,NK,N693NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,0.0,1700-1759,69.0,1814.0,2011.0,8.0,1921,58.0,1.0,3.0,1900-1959,9,0
142479,2022-03-28,Spirit Air Lines,EWR,LAS,False,False,1700,1802.0,62.0,62.0,2043.0,82.0,312.0,321.0,341.0,2227.0,2022,1,3,28,1,NK,NK,20416,NK,993,NK,20416,NK,N641NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,1.0,4.0,1700-1759,24.0,1826.0,2038.0,5.0,1921,82.0,1.0,5.0,1900-1959,9,0
142480,2022-03-29,Spirit Air Lines,EWR,LAS,False,False,1700,1654.0,0.0,-6.0,1912.0,0.0,300.0,321.0,318.0,2227.0,2022,1,3,29,2,NK,NK,20416,NK,993,NK,20416,NK,N623NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,-1.0,1700-1759,11.0,1705.0,1905.0,7.0,1921,-9.0,0.0,-1.0,1900-1959,9,0
142481,2022-03-30,Spirit Air Lines,EWR,LAS,False,False,1700,1709.0,9.0,9.0,2004.0,43.0,296.0,321.0,355.0,2227.0,2022,1,3,30,3,NK,NK,20416,NK,993,NK,20416,NK,N645NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,0.0,1700-1759,52.0,1801.0,1957.0,7.0,1921,43.0,1.0,2.0,1900-1959,9,0
142482,2022-03-31,Spirit Air Lines,EWR,LAS,True,False,1700,1804.0,64.0,64.0,NaN,NaN,NaN,321.0,NaN,2227.0,2022,1,3,31,4,NK,NK,20416,NK,993,NK,20416,NK,N650NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,1.0,4.0,1700-1759,NaN,NaN,NaN,NaN,1921,NaN,NaN,NaN,1900-1959,9,0

In [29]:
df.loc[(df['Airline'] == 'Spirit Air Lines') & (df['FlightDate'] == '2022-03-30')]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
123276,2022-03-30,Spirit Air Lines,FLL,ORD,False,False,2025,2103.0,38.0,38.0,2354.0,76.0,157.0,193.0,231.0,1182.0,2022,1,3,30,3,NK,NK,20416,NK,1,NK,20416,NK,N663NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,2.0,2000-2059,20.0,2123.0,2300.0,54.0,2238,76.0,1.0,5.0,2200-2259,5,0
123307,2022-03-30,Spirit Air Lines,ORD,FLL,False,False,515,517.0,2.0,2.0,916.0,1.0,151.0,180.0,179.0,1182.0,2022,1,3,30,3,NK,NK,20416,NK,2,NK,20416,NK,N687NK,2,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,0.0,0.0,0001-0559,23.0,540.0,911.0,5.0,915,1.0,0.0,0.0,0900-0959,5,0
123338,2022-03-30,Spirit Air Lines,ORD,FLL,False,False,755,759.0,4.0,4.0,1153.0,0.0,151.0,182.0,174.0,1182.0,2022,1,3,30,3,NK,NK,20416,NK,3,NK,20416,NK,N682NK,3,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,0.0,0.0,0700-0759,16.0,815.0,1146.0,7.0,1157,-4.0,0.0,-1.0,1100-1159,5,0
123369,2022-03-30,Spirit Air Lines,FLL,ORD,False,False,1637,1638.0,1.0,1.0,1844.0,0.0,161.0,193.0,186.0,1182.0,2022,1,3,30,3,NK,NK,20416,NK,6,NK,20416,NK,N674NK,6,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,0.0,1600-1659,11.0,1649.0,1830.0,14.0,1850,-6.0,0.0,-1.0,1800-1859,5,0
123424,2022-03-30,Spirit Air Lines,EWR,MYR,False,False,1350,1345.0,0.0,-5.0,1531.0,0.0,80.0,110.0,106.0,550.0,2022,1,3,30,3,NK,NK,20416,NK,54,NK,20416,NK,N696NK,54,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,13577,1357702,31135,"Myrtle Beach, SC",SC,45,South Carolina,37,0.0,-1.0,1300-1359,13.0,1358.0,1518.0,13.0,1540,-9.0,0.0,-1.0,1500-1559,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142358,2022-03-30,Spirit Air Lines,CLT,FLL,False,False,850,848.0,0.0,-2.0,1036.0,0.0,89.0,110.0,108.0,632.0,2022,1,3,30,3,NK,NK,20416,NK,980,NK,20416,NK,N616NK,980,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,0.0,-1.0,0800-0859,9.0,857.0,1026.0,10.0,1040,-4.0,0.0,-1.0,1000-1059,3,0
142388,2022-03-30,Spirit Air Lines,FLL,CLT,False,False,1420,1415.0,0.0,-5.0,1618.0,0.0,104.0,121.0,123.0,632.0,2022,1,3,30,3,NK,NK,20416,NK,981,NK,20416,NK,N936NK,981,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,0.0,-1.0,1400-1459,11.0,1426.0,1610.0,8.0,1621,-3.0,0.0,-1.0,1600-1659,3,0
142420,2022-03-30,Spirit Air Lines,DTW,MSY,False,False,1655,1651.0,0.0,-4.0,1825.0,0.0,132.0,150.0,154.0,926.0,2022,1,3,30,3,NK,NK,20416,NK,985,NK,20416,NK,N650NK,985,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,0.0,-1.0,1600-1659,9.0,1700.0,1812.0,13.0,1825,0.0,0.0,0.0,1800-1859,4,0
142451,2022-03-30,Spirit Air Lines,MSY,ORD,False,False,917,916.0,0.0,-1.0,1143.0,0.0,124.0,150.0,147.0,836.0,2022,1,3,30,3,NK,NK,20416,NK,992,NK,20416,NK,N634NK,992,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,0900-0959,11.0,927.0,1131.0,12.0,1147,-4.0,0.0,-1.0,1100-1159,4,0
142481,2022-03-30,Spirit Air Lines,EWR,LAS,False,False,1700,1709.0,9.0,9.0,2004.0,43.0,296.0,321.0,355.0,2227.0,2022,1,3,30,3,NK,NK,20416,NK,993,NK,20416,NK,N645NK,993,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,0.0,0.0,1700-1759,52.0,1801.0,1957.0,7.0,1921,43.0,1.0,2.0,1900-1959,9,0

In [30]:
df.loc[~((df['Airline'] == 'Spirit Air Lines') & (df['FlightDate'] == '2022-03-30'))]

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,1228.0,0.0,40.0,72.0,65.0,212.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4301,C5,20445,C5,N21144,4301,11921,1192102,31921,"Grand Junction, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,17.0,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,848.0,0.0,55.0,77.0,80.0,295.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4299,C5,20445,C5,N16170,4299,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,16.0,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
3,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",IAH,GPT,False,False,1435,1430.0,0.0,-5.0,1547.0,0.0,57.0,90.0,77.0,376.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4296,C5,20445,C5,N11184,4296,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,11973,1197302,31973,"Gulfport/Biloxi, MS",MS,28,Mississippi,53,0.0,-1.0,1400-1459,16.0,1446.0,1543.0,4.0,1605,-18.0,0.0,-2.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590537,2022-03-31,Republic Airlines,MSY,EWR,False,True,1949,2014.0,25.0,25.0,234.0,NaN,NaN,185.0,NaN,1167.0,2022,1,3,31,4,UA,UA_CODESHARE,19977,UA,3621,YX,20452,YX,N745YX,3621,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,1.0,1900-1959,17.0,2031.0,202.0,32.0,2354,NaN,NaN,NaN,2300-2359,5,1
590538,2022-03-17,Republic Airlines,CLT,EWR,True,False,1733,1817.0,44.0,44.0,NaN,NaN,NaN,129.0,NaN,529.0,2022,1,3,17,4,UA,UA_CODESHARE,19977,UA,3437,YX,20452,YX,N654RW,3437,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,2.0,1700-1759,NaN,NaN,NaN,NaN,1942,NaN,NaN,NaN,1900-1959,3,0
590539,2022-03-08,Republic Airlines,ALB,ORD,False,False,1700,2318.0,378.0,378.0,59.0,381.0,135.0,158.0,161.0,723.0,2022,1,3,8,2,UA,UA_CODESHARE,19977,UA,3413,YX,20452,YX,N733YX,3413,10257,1025702,30257,"Albany, NY",NY,36,New York,22,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,12.0,1700-1759,19.0,2337.0,52.0,7.0,1838,381.0,1.0,12.0,1800-1859,3,0
590540,2022-03-25,Republic Airlines,EWR,PIT,False,True,2129,2322.0,113.0,113.0,939.0,NaN,NaN,86.0,NaN,319.0,2022,1,3,25,5,UA,UA_CODESHARE,19977,UA,3450,YX,20452,YX,N647RW,3450,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,1.0,7.0,2100-2159,25.0,2347.0,933.0,6.0,2255,NaN,NaN,NaN,2200-2259,2,1
590541,2022-03-07,Republic Airlines,EWR,RDU,False,True,1154,1148.0,0.0,-6.0,1556.0,NaN,NaN,99.0,NaN,416.0,2022,1,3,7,1,UA,UA_CODESHARE,19977,UA,3585,YX,20452,YX,N648RW,3585,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14492,1449202,34492,"Raleigh/Durham, NC",NC,37,North Carolina,36,0.0,-1.0,1100-1159,13.0,1201.0,1552.0,4.0,1333,NaN,NaN,NaN,1300-1359,2,1

## query

In [31]:
df.query('DepTime > 1130 and (Origin == "DRO")')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
531,2022-04-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1524.0,0.0,-5.0,1633.0,0.0,50.0,70.0,69.0,251.0,2022,2,4,3,7,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N11191,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,9.0,1533.0,1623.0,10.0,1639,-6.0,0.0,-1.0,1600-1659,2,0
533,2022-04-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1134.0,0.0,-1.0,1247.0,2.0,43.0,70.0,73.0,251.0,2022,2,4,3,7,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N31131,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,19.0,1153.0,1236.0,11.0,1245,2.0,0.0,0.0,1200-1259,2,0
1003,2022-04-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1644.0,75.0,75.0,1757.0,78.0,46.0,70.0,73.0,251.0,2022,2,4,2,6,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N16151,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,5.0,1500-1559,15.0,1659.0,1745.0,12.0,1639,78.0,1.0,5.0,1600-1659,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445339,2022-03-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1521.0,0.0,-9.0,1645.0,5.0,50.0,70.0,84.0,251.0,2022,1,3,3,4,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N12163,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,27.0,1548.0,1638.0,7.0,1640,5.0,0.0,0.0,1600-1659,2,0
445977,2022-03-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1531.0,1.0,1.0,1651.0,11.0,50.0,70.0,80.0,251.0,2022,1,3,2,3,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N33182,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1500-1559,19.0,1550.0,1640.0,11.0,1640,11.0,0.0,0.0,1600-1659,2,0
445986,2022-03-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1142.0,7.0,7.0,1245.0,0.0,46.0,70.0,63.0,251.0,2022,1,3,2,3,UA,UA_CODESHARE,19977,UA,4281,C5,20445,C5,N33182,4281,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,11.0,1153.0,1239.0,6.0,1245,0.0,0.0,0.0,1200-1259,2,0
446617,2022-03-01,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1741.0,131.0,131.0,1909.0,149.0,52.0,70.0,88.0,251.0,2022,1,3,1,2,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N16178,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,8.0,1500-1559,25.0,1806.0,1858.0,11.0,1640,149.0,1.0,9.0,1600-1659,2,0
446626,2022-03-01,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1419.0,164.0,164.0,1523.0,158.0,46.0,70.0,64.0,251.0,2022,1,3,1,2,UA,UA_CODESHARE,19977,UA,4281,C5,20445,C5,N14174,4281,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,10.0,1100-1159,11.0,1430.0,1516.0,7.0,1245,158.0,1.0,10.0,1200-1259,2,0

In [32]:
# min_time = 1130
# df.query('DepTime > @min_time and (Origin == "DRO")')  # ValueError: Expression ((DepTime) > (__pd_eval_local_min_time)) & (Series_1_0x200x4c0x3a0x6c0xbf0x7d0x00x0) has forbidden control characters.

min_time = 1130
query_expression = 'DepTime > {} and (Origin == "DRO")'.format(min_time)
df.query(query_expression)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0
4,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1135.0,0.0,0.0,1251.0,6.0,49.0,70.0,76.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N17146,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,19.0,1154.0,1243.0,8.0,1245,6.0,0.0,0.0,1200-1259,2,0
531,2022-04-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1524.0,0.0,-5.0,1633.0,0.0,50.0,70.0,69.0,251.0,2022,2,4,3,7,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N11191,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,9.0,1533.0,1623.0,10.0,1639,-6.0,0.0,-1.0,1600-1659,2,0
533,2022-04-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1134.0,0.0,-1.0,1247.0,2.0,43.0,70.0,73.0,251.0,2022,2,4,3,7,UA,UA_CODESHARE,19977,UA,4295,C5,20445,C5,N31131,4295,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,19.0,1153.0,1236.0,11.0,1245,2.0,0.0,0.0,1200-1259,2,0
1003,2022-04-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1644.0,75.0,75.0,1757.0,78.0,46.0,70.0,73.0,251.0,2022,2,4,2,6,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N16151,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,5.0,1500-1559,15.0,1659.0,1745.0,12.0,1639,78.0,1.0,5.0,1600-1659,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445339,2022-03-03,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1521.0,0.0,-9.0,1645.0,5.0,50.0,70.0,84.0,251.0,2022,1,3,3,4,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N12163,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,27.0,1548.0,1638.0,7.0,1640,5.0,0.0,0.0,1600-1659,2,0
445977,2022-03-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1531.0,1.0,1.0,1651.0,11.0,50.0,70.0,80.0,251.0,2022,1,3,2,3,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N33182,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1500-1559,19.0,1550.0,1640.0,11.0,1640,11.0,0.0,0.0,1600-1659,2,0
445986,2022-03-02,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1142.0,7.0,7.0,1245.0,0.0,46.0,70.0,63.0,251.0,2022,1,3,2,3,UA,UA_CODESHARE,19977,UA,4281,C5,20445,C5,N33182,4281,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,0.0,1100-1159,11.0,1153.0,1239.0,6.0,1245,0.0,0.0,0.0,1200-1259,2,0
446617,2022-03-01,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1530,1741.0,131.0,131.0,1909.0,149.0,52.0,70.0,88.0,251.0,2022,1,3,1,2,UA,UA_CODESHARE,19977,UA,4292,C5,20445,C5,N16178,4292,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,8.0,1500-1559,25.0,1806.0,1858.0,11.0,1640,149.0,1.0,9.0,1600-1659,2,0
446626,2022-03-01,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1135,1419.0,164.0,164.0,1523.0,158.0,46.0,70.0,64.0,251.0,2022,1,3,1,2,UA,UA_CODESHARE,19977,UA,4281,C5,20445,C5,N14174,4281,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,1.0,10.0,1100-1159,11.0,1430.0,1516.0,7.0,1245,158.0,1.0,10.0,1200-1259,2,0

## Summary Statistics

In [33]:
df['DepTime'].min()

1.0

In [34]:
df['DepTime'].max()

2400.0

In [35]:
df['DepTime'].mean()

1334.3739312789533

In [36]:
df['DepTime'].std()

505.62193314209236

In [37]:
df['DepTime'].sum()

5281298567.0

In [38]:
df['DepTime'].quantile(0.5)

1325.0

In [39]:
df['DepTime'].quantile([0.25, 0.75])

0.25     917.0
0.75    1744.0
Name: DepTime, dtype: float64

## agg

In [40]:
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].agg(['mean', 'min', 'max'])

          DepTime     DepDelay      ArrTime     ArrDelay
mean  1334.373931    13.090487  1457.886018     7.528486
min      1.000000   -78.000000     1.000000  -100.000000
max   2400.000000  7223.000000  2400.000000  7232.000000

In [41]:
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].agg(
    {
        'DepTime': ['min', 'max'],
        'DepDelay': ['mean'],
        'ArrTime': ['min', 'max']
    }
)

      DepTime   DepDelay  ArrTime
min       1.0        NaN      1.0
max    2400.0        NaN   2400.0
mean      NaN  13.090487      NaN

## Summarize categoricals

In [42]:
df['Airline'].unique()

array(['Commutair Aka Champlain Enterprises, Inc.',
       'GoJet Airlines, LLC d/b/a United Express',
       'Air Wisconsin Airlines Corp', 'Mesa Airlines Inc.',
       'Southwest Airlines Co.', 'Republic Airlines', 'Endeavor Air Inc.',
       'American Airlines Inc.', 'Capital Cargo International',
       'SkyWest Airlines Inc.', 'Alaska Airlines Inc.', 'JetBlue Airways',
       'Delta Air Lines Inc.', 'Frontier Airlines Inc.', 'Allegiant Air',
       'Hawaiian Airlines Inc.', 'Envoy Air', 'Spirit Air Lines',
       'Comair Inc.', 'Horizon Air', 'United Air Lines Inc.'],
      dtype=object)

In [43]:
df['Airline'].nunique()

21

In [44]:
df['Airline'].value_counts()

Airline
Southwest Airlines Co.                       731925
Delta Air Lines Inc.                         512114
American Airlines Inc.                       495953
SkyWest Airlines Inc.                        440807
United Air Lines Inc.                        352009
Republic Airlines                            197881
JetBlue Airways                              156793
Envoy Air                                    150758
Endeavor Air Inc.                            142624
Comair Inc.                                  135884
Alaska Airlines Inc.                         129510
Spirit Air Lines                             129208
Frontier Airlines Inc.                        86557
Allegiant Air                                 73504
Mesa Airlines Inc.                            71972
Horizon Air                                   56320
Capital Cargo International                   52827
Commutair Aka Champlain Enterprises, Inc.     44367
Hawaiian Airlines Inc.                        42212
Air Wisconsin Airlines Corp                   40300
GoJet Airlines, LLC d/b/a United Express      34793
Name: count, dtype: int64

In [45]:
df[['Airline', 'Origin']].value_counts()

Airline                                    Origin
Delta Air Lines Inc.                       ATL       120919
American Airlines Inc.                     DFW        81239
                                           CLT        57914
United Air Lines Inc.                      DEN        46489
Southwest Airlines Co.                     DEN        45398
                                                      ...
Frontier Airlines Inc.                     ICT            1
Mesa Airlines Inc.                         MDT            1
Air Wisconsin Airlines Corp                FWA            1
Commutair Aka Champlain Enterprises, Inc.  DSM            1
GoJet Airlines, LLC d/b/a United Express   MKE            1
Name: count, Length: 2194, dtype: int64

In [46]:
df[['Airline', 'Origin']].value_counts().reset_index()

                                        Airline Origin   count
0                          Delta Air Lines Inc.    ATL  120919
1                        American Airlines Inc.    DFW   81239
2                        American Airlines Inc.    CLT   57914
3                         United Air Lines Inc.    DEN   46489
4                        Southwest Airlines Co.    DEN   45398
...                                         ...    ...     ...
2189                     Frontier Airlines Inc.    ICT       1
2190                         Mesa Airlines Inc.    MDT       1
2191                Air Wisconsin Airlines Corp    FWA       1
2192  Commutair Aka Champlain Enterprises, Inc.    DSM       1
2193   GoJet Airlines, LLC d/b/a United Express    MKE       1

[2194 rows x 3 columns]

## rank, shift, cumsum

In [47]:
df[['CRSDepTime']].rank(method='dense')

        CRSDepTime
0            574.0
1            333.0
2            810.0
3            756.0
4            576.0
...            ...
590537      1070.0
590538       934.0
590539       901.0
590540      1170.0
590541       595.0

[4078318 rows x 1 columns]

In [48]:
df[['CRSDepTime']].rank(method='first')

        CRSDepTime
0        1607043.0
1         594869.0
2        2547637.0
3        2338954.0
4        1610842.0
...            ...
590537   3576966.0
590538   3054522.0
590539   2925978.0
590540   3879124.0
590541   1679890.0

[4078318 rows x 1 columns]

In [49]:
df[['CRSDepTime']].shift(1)

        CRSDepTime
0              NaN
1           1133.0
2            732.0
3           1529.0
4           1435.0
...            ...
590537      2035.0
590538      1949.0
590539      1733.0
590540      1700.0
590541      2129.0

[4078318 rows x 1 columns]

In [50]:
df[['CRSDepTime']].shift(-1)

        CRSDepTime
0            732.0
1           1529.0
2           1435.0
3           1135.0
4            955.0
...            ...
590537      1733.0
590538      1700.0
590539      2129.0
590540      1154.0
590541         NaN

[4078318 rows x 1 columns]

In [51]:
df[['CRSDepTime']].shift(3, fill_value=100)

        CRSDepTime
0              100
1              100
2              100
3             1133
4              732
...            ...
590537        1750
590538        1829
590539        2035
590540        1949
590541        1733

[4078318 rows x 1 columns]

In [52]:
df[['CRSDepTime']].cumsum()

        CRSDepTime
0             1133
1             1865
2             3394
3             4829
4             5964
...            ...
590537  5422470512
590538  5422472245
590539  5422473945
590540  5422476074
590541  5422477228

[4078318 rows x 1 columns]

In [53]:
df[['CRSDepTime']].cummax()

        CRSDepTime
0             1133
1             1133
2             1529
3             1529
4             1529
...            ...
590537        2359
590538        2359
590539        2359
590540        2359
590541        2359

[4078318 rows x 1 columns]

In [54]:
df[['CRSDepTime']].cummin()

        CRSDepTime
0             1133
1              732
2              732
3              732
4              732
...            ...
590537           1
590538           1
590539           1
590540           1
590541           1

[4078318 rows x 1 columns]

## Rolling methods

In [55]:
df[['DepDelayMinutes']].rolling(window=5).mean()

        DepDelayMinutes
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   0.0
...                 ...
590537            144.2
590538            108.4
590539            145.0
590540            142.8
590541            112.0

[4078318 rows x 1 columns]

## Clip

In [56]:
df['DepTime'].clip(1000, 2000)

0         1123.0
1         1000.0
2         1514.0
3         1430.0
4         1135.0
           ...
590537    2000.0
590538    1817.0
590539    2000.0
590540    2000.0
590541    1148.0
Name: DepTime, Length: 4078318, dtype: float64

## Groupby

In [18]:
df.describe(include= 'object')

,Airline,Origin,Dest,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,IATA_Code_Marketing_Airline,Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,OriginCityName,OriginState,OriginStateName,DestCityName,DestState,DestStateName,DepTimeBlk,ArrTimeBlk
count,4078318,4078318,4078318,4078318,4078318,4078318,4078318,4078318,4051523,4078318,4078318,4078318,4078318,4078318,4078318,4078318,4078318
unique,21,375,375,10,14,10,21,21,5896,369,53,53,369,53,53,19,19
top,Southwest Airlines Co.,ATL,ATL,AA,WN,AA,WN,WN,N475HA,"Chicago, IL",TX,Texas,"Chicago, IL",TX,Texas,0600-0659,1200-1259
freq,731925,183697,183671,1043530,731925,1043530,731925,731925,1657,213487,426204,426204,213516,426207,426207,286192,256772

In [57]:
df.groupby('Airline')[['DepDelay']].mean()

                                            DepDelay
Airline
Air Wisconsin Airlines Corp                 7.913244
Alaska Airlines Inc.                        5.925950
Allegiant Air                              19.061569
American Airlines Inc.                     14.876556
Capital Cargo International                 6.044430
Comair Inc.                                12.693968
Commutair Aka Champlain Enterprises, Inc.  12.093640
Delta Air Lines Inc.                       11.398599
Endeavor Air Inc.                           9.696390
Envoy Air                                   6.883448
Frontier Airlines Inc.                     20.052761
GoJet Airlines, LLC d/b/a United Express   16.741980
Hawaiian Airlines Inc.                      6.612163
Horizon Air                                 5.892804
JetBlue Airways                            26.009890
Mesa Airlines Inc.                         15.714753
Republic Airlines                          10.811487
SkyWest Airlines Inc.                      11.247036
Southwest Airlines Co.                     14.563121
Spirit Air Lines                           15.621816
United Air Lines Inc.                      13.730542

In [58]:
df.groupby('Airline')[['DepDelay']].agg(['mean', 'min', 'max'])

                                            DepDelay
                                                mean   min     max
Airline
Air Wisconsin Airlines Corp                 7.913244 -30.0  1355.0
Alaska Airlines Inc.                        5.925950 -63.0   915.0
Allegiant Air                              19.061569 -37.0  1917.0
American Airlines Inc.                     14.876556 -35.0  2994.0
Capital Cargo International                 6.044430 -34.0  1512.0
Comair Inc.                                12.693968 -49.0  1607.0
Commutair Aka Champlain Enterprises, Inc.  12.093640 -27.0  1464.0
Delta Air Lines Inc.                       11.398599 -38.0  1287.0
Endeavor Air Inc.                           9.696390 -34.0  1973.0
Envoy Air                                   6.883448 -29.0  5327.0
Frontier Airlines Inc.                     20.052761 -40.0  1288.0
GoJet Airlines, LLC d/b/a United Express   16.741980 -43.0  1220.0
Hawaiian Airlines Inc.                      6.612163 -32.0  1847.0
Horizon Air                                 5.892804 -38.0   803.0
JetBlue Airways                            26.009890 -56.0  2052.0
Mesa Airlines Inc.                         15.714753 -35.0  1837.0
Republic Airlines                          10.811487 -55.0  7223.0
SkyWest Airlines Inc.                      11.247036 -55.0  2366.0
Southwest Airlines Co.                     14.563121 -52.0   747.0
Spirit Air Lines                           15.621816 -39.0  1436.0
United Air Lines Inc.                      13.730542 -78.0  1520.0

In [59]:
df_agg = df.groupby('Airline')[['DepDelay', 'ArrDelay']].agg(['mean', 'min', 'max'])

In [60]:
df_agg.columns

MultiIndex([('DepDelay', 'mean'),
            ('DepDelay',  'min'),
            ('DepDelay',  'max'),
            ('ArrDelay', 'mean'),
            ('ArrDelay',  'min'),
            ('ArrDelay',  'max')],
           )

In [61]:
df_agg.columns.to_flat_index()

Index([('DepDelay', 'mean'),  ('DepDelay', 'min'),  ('DepDelay', 'max'),
       ('ArrDelay', 'mean'),  ('ArrDelay', 'min'),  ('ArrDelay', 'max')],
      dtype='object')

In [62]:
df_agg.columns = ["_".join(c) for c in df_agg.columns]

In [63]:
df_agg

,DepDelay_mean,DepDelay_min,DepDelay_max,ArrDelay_mean,ArrDelay_min,ArrDelay_max
Airline,,,,,,
Air Wisconsin Airlines Corp,7.913244,-30.0,1355.0,1.819183,-63.0,1353.0
Alaska Airlines Inc.,5.925950,-63.0,915.0,3.170588,-76.0,908.0
Allegiant Air,19.061569,-37.0,1917.0,20.519645,-69.0,1919.0
American Airlines Inc.,14.876556,-35.0,2994.0,9.528696,-80.0,2977.0
Capital Cargo International,6.044430,-34.0,1512.0,2.627024,-52.0,1490.0
Comair Inc.,12.693968,-49.0,1607.0,9.339501,-65.0,1612.0
"Commutair Aka Champlain Enterprises, Inc.",12.093640,-27.0,1464.0,8.018588,-62.0,1456.0
Delta Air Lines Inc.,11.398599,-38.0,1287.0,3.925805,-86.0,1285.0
Endeavor Air Inc.,9.696390,-34.0,1973.0,4.164953,-61.0,1968.0
Envoy Air,6.883448,-29.0,5327.0,2.381778,-60.0,5324.0
Frontier Airlines Inc.,20.052761,-40.0,1288.0,17.218371,-72.0,1311.0
"GoJet Airlines, LLC d/b/a United Express",16.741980,-43.0,1220.0,12.887419,-58.0,1199.0
Hawaiian Airlines Inc.,6.612163,-32.0,1847.0,4.489443,-65.0,1805.0
Horizon Air,5.892804,-38.0,803.0,4.278277,-41.0,803.0
JetBlue Airways,26.009890,-56.0,2052.0,20.009015,-100.0,2029.0
Mesa Airlines Inc.,15.714753,-35.0,1837.0,8.766944,-77.0,1818.0
Republic Airlines,10.811487,-55.0,7223.0,7.208726,-81.0,7232.0
SkyWest Airlines Inc.,11.247036,-55.0,2366.0,5.964007,-73.0,2363.0
Southwest Airlines Co.,14.563121,-52.0,747.0,7.176226,-69.0,731.0
Spirit Air Lines,15.621816,-39.0,1436.0,12.234907,-55.0,1436.0
United Air Lines Inc.,13.730542,-78.0,1520.0,6.624249,-75.0,1496.0

## New columns

In [59]:
df['DepTime2'] = df['DepTime'] / 60
df.head(3)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,1228.0,0.0,40.0,72.0,65.0,212.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4301,C5,20445,C5,N21144,4301,11921,1192102,31921,"Grand Junction, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,17.0,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0,18.716667
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,848.0,0.0,55.0,77.0,80.0,295.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4299,C5,20445,C5,N16170,4299,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,16.0,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0,12.133333
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0,25.233333

In [66]:
df = df.assign(DepTime3 = df['DepTime'] / 60)
df.head(3)

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2,DepTime3
0,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",GJT,DEN,False,False,1133,1123.0,0.0,-10.0,1228.0,0.0,40.0,72.0,65.0,212.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4301,C5,20445,C5,N21144,4301,11921,1192102,31921,"Grand Junction, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1100-1159,17.0,1140.0,1220.0,8.0,1245,-17.0,0.0,-2.0,1200-1259,1,0,18.716667,18.716667
1,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",HRL,IAH,False,False,732,728.0,0.0,-4.0,848.0,0.0,55.0,77.0,80.0,295.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4299,C5,20445,C5,N16170,4299,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,16.0,744.0,839.0,9.0,849,-1.0,0.0,-1.0,0800-0859,2,0,12.133333,12.133333
2,2022-04-04,"Commutair Aka Champlain Enterprises, Inc.",DRO,DEN,False,False,1529,1514.0,0.0,-15.0,1636.0,0.0,47.0,70.0,82.0,251.0,2022,2,4,4,1,UA,UA_CODESHARE,19977,UA,4298,C5,20445,C5,N21144,4298,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,0.0,-1.0,1500-1559,21.0,1535.0,1622.0,14.0,1639,-3.0,0.0,-1.0,1600-1659,2,0,25.233333,25.233333

## Sorting

In [67]:
df.sort_values('ArrDelay')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2,DepTime3
412626,2022-01-20,JetBlue Airways,STT,EWR,False,False,1242,1223.0,0.0,-19.0,1542.0,0.0,236.0,340.0,259.0,1634.0,2022,1,1,20,4,B6,B6,20409,B6,886,B6,20409,B6,N775JB,886,15024,1502403,34945,"Charlotte Amalie, VI",VI,78,U.S. Virgin Islands,4,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,0.0,-2.0,1200-1259,15.0,1238.0,1534.0,8.0,1722,-100.0,0.0,-2.0,1700-1759,7,0,20.383333,20.383333
268256,2022-03-30,JetBlue Airways,STT,JFK,False,False,1641,1626.0,0.0,-15.0,2024.0,0.0,222.0,318.0,238.0,1623.0,2022,1,3,30,3,B6,B6,20409,B6,830,B6,20409,B6,N2039J,830,15024,1502403,34945,"Charlotte Amalie, VI",VI,78,U.S. Virgin Islands,4,12478,1247805,31703,"New York, NY",NY,36,New York,22,0.0,-1.0,1600-1659,10.0,1636.0,2018.0,6.0,2159,-95.0,0.0,-2.0,2100-2159,7,0,27.100000,27.100000
398369,2022-01-22,JetBlue Airways,STT,JFK,False,False,1812,1810.0,0.0,-2.0,2102.0,0.0,210.0,321.0,232.0,1623.0,2022,1,1,22,6,B6,B6,20409,B6,830,B6,20409,B6,N2105J,830,15024,1502403,34945,"Charlotte Amalie, VI",VI,78,U.S. Virgin Islands,4,12478,1247805,31703,"New York, NY",NY,36,New York,22,0.0,-1.0,1800-1859,10.0,1820.0,2050.0,12.0,2233,-91.0,0.0,-2.0,2200-2259,7,0,30.166667,30.166667
284876,2022-04-12,Delta Air Lines Inc.,SAN,ATL,False,False,1300,1259.0,0.0,-1.0,1959.0,0.0,209.0,325.0,240.0,1892.0,2022,2,4,12,2,DL,DL,19790,DL,350,DL,19790,DL,N723TW,350,14679,1467903,33570,"San Diego, CA",CA,6,California,91,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,-1.0,1300-1359,25.0,1324.0,1953.0,6.0,2125,-86.0,0.0,-2.0,2100-2159,8,0,20.983333,20.983333
583512,2022-05-12,Republic Airlines,LGA,IAH,False,False,1315,1302.0,0.0,-13.0,1520.0,0.0,168.0,266.0,198.0,1416.0,2022,2,5,12,4,AA,AA_CODESHARE,19805,AA,4816,YX,20452,YX,N420YX,4816,12953,1295304,31703,"New York, NY",NY,36,New York,22,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,1300-1359,21.0,1323.0,1511.0,9.0,1641,-81.0,0.0,-2.0,1600-1659,6,0,21.700000,21.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590535,2022-03-31,Republic Airlines,EWR,PIT,True,False,1829,2033.0,124.0,124.0,NaN,NaN,NaN,97.0,NaN,319.0,2022,1,3,31,4,UA,UA_CODESHARE,19977,UA,3687,YX,20452,YX,N651RW,3687,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,1.0,8.0,1800-1859,NaN,NaN,NaN,NaN,2006,NaN,NaN,NaN,2000-2059,2,0,33.883333,33.883333
590537,2022-03-31,Republic Airlines,MSY,EWR,False,True,1949,2014.0,25.0,25.0,234.0,NaN,NaN,185.0,NaN,1167.0,2022,1,3,31,4,UA,UA_CODESHARE,19977,UA,3621,YX,20452,YX,N745YX,3621,13495,1349505,33495,"New Orleans, LA",LA,22,Louisiana,72,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,1.0,1900-1959,17.0,2031.0,202.0,32.0,2354,NaN,NaN,NaN,2300-2359,5,1,33.566667,33.566667
590538,2022-03-17,Republic Airlines,CLT,EWR,True,False,1733,1817.0,44.0,44.0,NaN,NaN,NaN,129.0,NaN,529.0,2022,1,3,17,4,UA,UA_CODESHARE,19977,UA,3437,YX,20452,YX,N654RW,3437,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,2.0,1700-1759,NaN,NaN,NaN,NaN,1942,NaN,NaN,NaN,1900-1959,3,0,30.283333,30.283333
590540,2022-03-25,Republic Airlines,EWR,PIT,False,True,2129,2322.0,113.0,113.0,939.0,NaN,NaN,86.0,NaN,319.0,2022,1,3,25,5,UA,UA_CODESHARE,19977,UA,3450,YX,20452,YX,N647RW,3450,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14122,1412202,30198,"Pittsburgh, PA",PA,42,Pennsylvania,23,1.0,7.0,2100-2159,25.0,2347.0,933.0,6.0,2255,NaN,NaN,NaN,2200-2259,2,1,38.700000,38.700000
590541,2022-03-07,Republic Airlines,EWR,RDU,False,True,1154,1148.0,0.0,-6.0,1556.0,NaN,NaN,99.0,NaN,416.0,2022,1,3,7,1,UA,UA_CODESHARE,19977,UA,3585,YX,20452,YX,N648RW,3585,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,14492,1449202,34492,"Raleigh/Durham, NC",NC,37,North Carolina,36,0.0,-1.0,1100-1159,13.0,1201.0,1552.0,4.0,1333,NaN,NaN,NaN,1300-1359,2,1,19.133333,19.133333

In [68]:
df[['FlightDate', 'Airline', 'ArrDelay']].sort_values('ArrDelay', ascending=False)

       FlightDate                 Airline  ArrDelay
249863 2022-05-23       Republic Airlines    7232.0
553561 2022-06-18               Envoy Air    5324.0
249859 2022-05-16       Republic Airlines    4318.0
485902 2022-06-05  American Airlines Inc.    2977.0
190829 2022-03-26  American Airlines Inc.    2934.0
...           ...                     ...       ...
590535 2022-03-31       Republic Airlines       NaN
590537 2022-03-31       Republic Airlines       NaN
590538 2022-03-17       Republic Airlines       NaN
590540 2022-03-25       Republic Airlines       NaN
590541 2022-03-07       Republic Airlines       NaN

[4078318 rows x 3 columns]

In [69]:
df[['FlightDate', 'Airline', 'ArrDelay']].sort_values('ArrDelay', ascending=False).reset_index(drop=True)

        FlightDate                 Airline  ArrDelay
0       2022-05-23       Republic Airlines    7232.0
1       2022-06-18               Envoy Air    5324.0
2       2022-05-16       Republic Airlines    4318.0
3       2022-06-05  American Airlines Inc.    2977.0
4       2022-03-26  American Airlines Inc.    2934.0
...            ...                     ...       ...
4078313 2022-03-31       Republic Airlines       NaN
4078314 2022-03-31       Republic Airlines       NaN
4078315 2022-03-17       Republic Airlines       NaN
4078316 2022-03-25       Republic Airlines       NaN
4078317 2022-03-07       Republic Airlines       NaN

[4078318 rows x 3 columns]

In [70]:
df[['FlightDate', 'Airline', 'ArrDelay']].sort_index()

       FlightDate                                    Airline  ArrDelay
0      2022-04-04  Commutair Aka Champlain Enterprises, Inc.     -17.0
0      2022-05-03                                Comair Inc.       1.0
0      2022-01-06                       Delta Air Lines Inc.       NaN
0      2022-07-19                                Comair Inc.     -29.0
0      2022-03-08                       Delta Air Lines Inc.     -14.0
...           ...                                        ...       ...
618785 2022-07-01                          Republic Airlines      18.0
618786 2022-07-01                          Republic Airlines     -25.0
618787 2022-07-01                          Republic Airlines      20.0
618788 2022-07-01                          Republic Airlines      43.0
618789 2022-07-01                          Republic Airlines     183.0

[4078318 rows x 3 columns]

## Missing data

In [71]:
df[['FlightDate', 'Airline', 'ArrDelay']].isna()

        FlightDate  Airline  ArrDelay
0            False    False     False
1            False    False     False
2            False    False     False
3            False    False     False
4            False    False     False
...            ...      ...       ...
590537       False    False      True
590538       False    False      True
590539       False    False     False
590540       False    False      True
590541       False    False      True

[4078318 rows x 3 columns]

In [72]:
df[['FlightDate', 'Airline', 'ArrDelay']].isna().sum()

FlightDate         0
Airline            0
ArrDelay      133402
dtype: int64

In [73]:
df[['FlightDate', 'Airline', 'ArrDelay']].dropna(subset=['ArrDelay'])

       FlightDate                                    Airline  ArrDelay
0      2022-04-04  Commutair Aka Champlain Enterprises, Inc.     -17.0
1      2022-04-04  Commutair Aka Champlain Enterprises, Inc.      -1.0
2      2022-04-04  Commutair Aka Champlain Enterprises, Inc.      -3.0
3      2022-04-04  Commutair Aka Champlain Enterprises, Inc.     -18.0
4      2022-04-04  Commutair Aka Champlain Enterprises, Inc.       6.0
...           ...                                        ...       ...
590532 2022-03-31                          Republic Airlines     207.0
590533 2022-03-31                          Republic Airlines     201.0
590534 2022-03-31                          Republic Airlines     180.0
590536 2022-03-19                          Republic Airlines     135.0
590539 2022-03-08                          Republic Airlines     381.0

[3944916 rows x 3 columns]

In [74]:
df[['FlightDate', 'Airline', 'ArrDelay']].fillna(-999)

       FlightDate                                    Airline  ArrDelay
0      2022-04-04  Commutair Aka Champlain Enterprises, Inc.     -17.0
1      2022-04-04  Commutair Aka Champlain Enterprises, Inc.      -1.0
2      2022-04-04  Commutair Aka Champlain Enterprises, Inc.      -3.0
3      2022-04-04  Commutair Aka Champlain Enterprises, Inc.     -18.0
4      2022-04-04  Commutair Aka Champlain Enterprises, Inc.       6.0
...           ...                                        ...       ...
590537 2022-03-31                          Republic Airlines    -999.0
590538 2022-03-17                          Republic Airlines    -999.0
590539 2022-03-08                          Republic Airlines     381.0
590540 2022-03-25                          Republic Airlines    -999.0
590541 2022-03-07                          Republic Airlines    -999.0

[4078318 rows x 3 columns]

In [75]:
df['ArrDelay'].fillna(df['ArrDelay'].mean())

0         -17.000000
1          -1.000000
2          -3.000000
3         -18.000000
4           6.000000
             ...
590537      7.528486
590538      7.528486
590539    381.000000
590540      7.528486
590541      7.528486
Name: ArrDelay, Length: 4078318, dtype: float64

## Concat

In [76]:
df1 = df.query('Airline == "Southwest Airlines Co."').copy()
df2 = df.query('Airline == "Delta Air Lines Inc."').copy()

In [77]:
pd.concat([df1, df2])

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2,DepTime3
1821,2022-04-01,Southwest Airlines Co.,ABQ,AUS,False,False,1035,1037.0,2.0,2.0,1303.0,0.0,75.0,100.0,86.0,619.0,2022,2,4,1,5,WN,WN,19393,WN,236,WN,19393,WN,N232WN,236,10140,1014005,30140,"Albuquerque, NM",NM,35,New Mexico,86,10423,1042302,30423,"Austin, TX",TX,48,Texas,74,0.0,0.0,1000-1059,8.0,1045.0,1300.0,3.0,1315,-12.0,0.0,-1.0,1300-1359,3,0,17.283333,17.283333
1822,2022-04-01,Southwest Airlines Co.,ABQ,BUR,False,False,1750,1823.0,33.0,33.0,1914.0,24.0,96.0,120.0,111.0,672.0,2022,2,4,1,5,WN,WN,19393,WN,1238,WN,19393,WN,N248WN,1238,10140,1014005,30140,"Albuquerque, NM",NM,35,New Mexico,86,10800,1080003,32575,"Burbank, CA",CA,6,California,91,1.0,2.0,1700-1759,13.0,1836.0,1912.0,2.0,1850,24.0,1.0,1.0,1800-1859,3,0,30.383333,30.383333
1823,2022-04-01,Southwest Airlines Co.,ABQ,DAL,False,False,645,648.0,3.0,3.0,922.0,0.0,79.0,105.0,94.0,580.0,2022,2,4,1,5,WN,WN,19393,WN,100,WN,19393,WN,N206WN,100,10140,1014005,30140,"Albuquerque, NM",NM,35,New Mexico,86,11259,1125904,30194,"Dallas, TX",TX,48,Texas,74,0.0,0.0,0600-0659,13.0,701.0,920.0,2.0,930,-8.0,0.0,-1.0,0900-0959,3,0,10.800000,10.800000
1824,2022-04-01,Southwest Airlines Co.,ABQ,DAL,False,False,1150,1146.0,0.0,-4.0,1439.0,4.0,76.0,105.0,113.0,580.0,2022,2,4,1,5,WN,WN,19393,WN,869,WN,19393,WN,N8689C,869,10140,1014005,30140,"Albuquerque, NM",NM,35,New Mexico,86,11259,1125904,30194,"Dallas, TX",TX,48,Texas,74,0.0,-1.0,1100-1159,9.0,1155.0,1411.0,28.0,1435,4.0,0.0,0.0,1400-1459,3,0,19.100000,19.100000
1825,2022-04-01,Southwest Airlines Co.,ABQ,DAL,False,False,1730,1757.0,27.0,27.0,2042.0,32.0,83.0,100.0,105.0,580.0,2022,2,4,1,5,WN,WN,19393,WN,1256,WN,19393,WN,N774SW,1256,10140,1014005,30140,"Albuquerque, NM",NM,35,New Mexico,86,11259,1125904,30194,"Dallas, TX",TX,48,Texas,74,1.0,1.0,1700-1759,13.0,1810.0,2033.0,9.0,2010,32.0,1.0,2.0,2000-2059,3,0,29.283333,29.283333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295256,2022-03-28,Delta Air Lines Inc.,DTW,PWM,False,False,2120,2118.0,0.0,-2.0,2315.0,7.0,90.0,108.0,117.0,668.0,2022,1,3,28,1,DL,DL,19790,DL,470,DL,19790,DL,N369NB,470,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,14321,1432105,34321,"Portland, ME",ME,23,Maine,12,0.0,-1.0,2100-2159,10.0,2128.0,2258.0,17.0,2308,7.0,0.0,0.0,2300-2359,3,0,35.300000,35.300000
295257,2022-03-29,Delta Air Lines Inc.,DTW,PWM,False,False,2120,2116.0,0.0,-4.0,2255.0,0.0,86.0,108.0,99.0,668.0,2022,1,3,29,2,DL,DL,19790,DL,470,DL,19790,DL,N361NB,470,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,14321,1432105,34321,"Portland, ME",ME,23,Maine,12,0.0,-1.0,2100-2159,10.0,2126.0,2252.0,3.0,2308,-13.0,0.0,-1.0,2300-2359,3,0,35.266667,35.266667
295258,2022-03-30,Delta Air Lines Inc.,DTW,PWM,False,False,2120,2108.0,0.0,-12.0,2246.0,0.0,81.0,108.0,98.0,668.0,2022,1,3,30,3,DL,DL,19790,DL,470,DL,19790,DL,N315NB,470,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,14321,1432105,34321,"Portland, ME",ME,23,Maine,12,0.0,-1.0,2100-2159,14.0,2122.0,2243.0,3.0,2308,-22.0,0.0,-2.0,2300-2359,3,0,35.133333,35.133333
295259,2022-03-31,Delta Air Lines Inc.,DTW,PWM,False,False,2120,2142.0,22.0,22.0,2325.0,17.0,85.0,108.0,103.0,668.0,2022,1,3,31,4,DL,DL,19790,DL,470,DL,19790,DL,N354NB,470,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,14321,1432105,34321,"Portland, ME",ME,23,Maine,12,1.0,1.0,2100-2159,14.0,2156.0,2321.0,4.0,2308,17.0,1.0,1.0,2300-2359,3,0,35.700000,35.700000
295260,2022-03-07,Delta Air Lines Inc.,ATL,DTW,False,False,1000,959.0,0.0,-1.0,1144.0,0.0,80.0,110.0,105.0,594.0,2022,1,3,7,1,DL,DL,19790,DL,471,DL,19790,DL,N504DN,471,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,0.0,-1.0,1000-1059,16.0,1015.0,1135.0,9.0,1150,-6.0,0.0,-1.0,1100-1159,3,0,15.983333,15.983333

In [78]:
df_stack = pd.concat([df1, df2])

In [79]:
df1 = df1.reset_index(drop=True)
df2 = df2.reset_index(drop=True)

In [80]:
df_side = pd.concat([df1, df2], axis=1)

In [81]:
df1.shape, df2.shape, df_stack.shape, df_side.shape

((731925, 63), (512114, 63), (1244039, 63), (731925, 126))

## Merge dataframes

In [82]:
df1 = df.groupby(['Airline', 'FlightDate'])[['DepDelay']].mean().reset_index()
df2 = df.groupby(['Airline', 'FlightDate'])[['ArrDelay']].mean().reset_index()

In [83]:
df2

                          Airline FlightDate   ArrDelay
0     Air Wisconsin Airlines Corp 2022-01-01   5.717949
1     Air Wisconsin Airlines Corp 2022-01-02  36.641176
2     Air Wisconsin Airlines Corp 2022-01-03  36.525316
3     Air Wisconsin Airlines Corp 2022-01-04  -5.842391
4     Air Wisconsin Airlines Corp 2022-01-05  20.250000
...                           ...        ...        ...
4447        United Air Lines Inc. 2022-07-27   4.912778
4448        United Air Lines Inc. 2022-07-28   6.640288
4449        United Air Lines Inc. 2022-07-29   4.629425
4450        United Air Lines Inc. 2022-07-30  -4.716889
4451        United Air Lines Inc. 2022-07-31   4.626857

[4452 rows x 3 columns]

In [84]:
df1.merge(df2, how="left")

                          Airline FlightDate   DepDelay   ArrDelay
0     Air Wisconsin Airlines Corp 2022-01-01   8.784810   5.717949
1     Air Wisconsin Airlines Corp 2022-01-02  41.766082  36.641176
2     Air Wisconsin Airlines Corp 2022-01-03  46.183544  36.525316
3     Air Wisconsin Airlines Corp 2022-01-04   6.141304  -5.842391
4     Air Wisconsin Airlines Corp 2022-01-05  20.532967  20.250000
...                           ...        ...        ...        ...
4447        United Air Lines Inc. 2022-07-27  12.064677   4.912778
4448        United Air Lines Inc. 2022-07-28  14.437948   6.640288
4449        United Air Lines Inc. 2022-07-29  11.029185   4.629425
4450        United Air Lines Inc. 2022-07-30   6.192961  -4.716889
4451        United Air Lines Inc. 2022-07-31  12.688534   4.626857

[4452 rows x 4 columns]

In [85]:
df1.merge(df2, how="right")

                          Airline FlightDate   DepDelay   ArrDelay
0     Air Wisconsin Airlines Corp 2022-01-01   8.784810   5.717949
1     Air Wisconsin Airlines Corp 2022-01-02  41.766082  36.641176
2     Air Wisconsin Airlines Corp 2022-01-03  46.183544  36.525316
3     Air Wisconsin Airlines Corp 2022-01-04   6.141304  -5.842391
4     Air Wisconsin Airlines Corp 2022-01-05  20.532967  20.250000
...                           ...        ...        ...        ...
4447        United Air Lines Inc. 2022-07-27  12.064677   4.912778
4448        United Air Lines Inc. 2022-07-28  14.437948   6.640288
4449        United Air Lines Inc. 2022-07-29  11.029185   4.629425
4450        United Air Lines Inc. 2022-07-30   6.192961  -4.716889
4451        United Air Lines Inc. 2022-07-31  12.688534   4.626857

[4452 rows x 4 columns]

In [86]:
df1.merge(df2, how="outer")

                          Airline FlightDate   DepDelay   ArrDelay
0     Air Wisconsin Airlines Corp 2022-01-01   8.784810   5.717949
1     Air Wisconsin Airlines Corp 2022-01-02  41.766082  36.641176
2     Air Wisconsin Airlines Corp 2022-01-03  46.183544  36.525316
3     Air Wisconsin Airlines Corp 2022-01-04   6.141304  -5.842391
4     Air Wisconsin Airlines Corp 2022-01-05  20.532967  20.250000
...                           ...        ...        ...        ...
4447        United Air Lines Inc. 2022-07-27  12.064677   4.912778
4448        United Air Lines Inc. 2022-07-28  14.437948   6.640288
4449        United Air Lines Inc. 2022-07-29  11.029185   4.629425
4450        United Air Lines Inc. 2022-07-30   6.192961  -4.716889
4451        United Air Lines Inc. 2022-07-31  12.688534   4.626857

[4452 rows x 4 columns]

## Merge suffixes

In [87]:
pd.merge(df1, df2, on=['Airline', 'FlightDate'])

                          Airline FlightDate   DepDelay   ArrDelay
0     Air Wisconsin Airlines Corp 2022-01-01   8.784810   5.717949
1     Air Wisconsin Airlines Corp 2022-01-02  41.766082  36.641176
2     Air Wisconsin Airlines Corp 2022-01-03  46.183544  36.525316
3     Air Wisconsin Airlines Corp 2022-01-04   6.141304  -5.842391
4     Air Wisconsin Airlines Corp 2022-01-05  20.532967  20.250000
...                           ...        ...        ...        ...
4447        United Air Lines Inc. 2022-07-27  12.064677   4.912778
4448        United Air Lines Inc. 2022-07-28  14.437948   6.640288
4449        United Air Lines Inc. 2022-07-29  11.029185   4.629425
4450        United Air Lines Inc. 2022-07-30   6.192961  -4.716889
4451        United Air Lines Inc. 2022-07-31  12.688534   4.626857

[4452 rows x 4 columns]

In [88]:
pd.merge(df1, df2, on=['Airline'])

,Airline,FlightDate_x,DepDelay,FlightDate_y,ArrDelay
0,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-01,5.717949
1,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-02,36.641176
2,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-03,36.525316
3,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-04,-5.842391
4,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-05,20.250000
...,...,...,...,...,...
943819,United Air Lines Inc.,2022-07-31,12.688534,2022-07-27,4.912778
943820,United Air Lines Inc.,2022-07-31,12.688534,2022-07-28,6.640288
943821,United Air Lines Inc.,2022-07-31,12.688534,2022-07-29,4.629425
943822,United Air Lines Inc.,2022-07-31,12.688534,2022-07-30,-4.716889
943823,United Air Lines Inc.,2022-07-31,12.688534,2022-07-31,4.626857

In [89]:
pd.merge(df1, df2, on=['Airline'], suffixes=('_dep', '_arr'))

,Airline,FlightDate_dep,DepDelay,FlightDate_arr,ArrDelay
0,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-01,5.717949
1,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-02,36.641176
2,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-03,36.525316
3,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-04,-5.842391
4,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-05,20.250000
...,...,...,...,...,...
943819,United Air Lines Inc.,2022-07-31,12.688534,2022-07-27,4.912778
943820,United Air Lines Inc.,2022-07-31,12.688534,2022-07-28,6.640288
943821,United Air Lines Inc.,2022-07-31,12.688534,2022-07-29,4.629425
943822,United Air Lines Inc.,2022-07-31,12.688534,2022-07-30,-4.716889
943823,United Air Lines Inc.,2022-07-31,12.688534,2022-07-31,4.626857

In [90]:
pd.merge(df1, df2, left_on=['Airline'], right_on=['Airline'])

,Airline,FlightDate_x,DepDelay,FlightDate_y,ArrDelay
0,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-01,5.717949
1,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-02,36.641176
2,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-03,36.525316
3,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-04,-5.842391
4,Air Wisconsin Airlines Corp,2022-01-01,8.784810,2022-01-05,20.250000
...,...,...,...,...,...
943819,United Air Lines Inc.,2022-07-31,12.688534,2022-07-27,4.912778
943820,United Air Lines Inc.,2022-07-31,12.688534,2022-07-28,6.640288
943821,United Air Lines Inc.,2022-07-31,12.688534,2022-07-29,4.629425
943822,United Air Lines Inc.,2022-07-31,12.688534,2022-07-30,-4.716889
943823,United Air Lines Inc.,2022-07-31,12.688534,2022-07-31,4.626857